baseurl =  
title = "Fresbin Thomas" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Fresbin Thomas" # Author's name.
    info = "Masters Student in Riga Technical University" # Author's job title or info.
    description = "Fresbin's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/fres.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableInstagramShare = true   # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Fresbin"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/fresbin/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/fresbin-thomas-6232b4116/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "Whatsapp"
    icon = "fab fa-whatsapp"
    weight = 4
    url = "https://www.whatsapp.com"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 5
    url = "https://www.facebook.com/fresbin.thomas"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 6
    url = "https://www.instagram.com/fressu.me/"    
# Menu links
[[menu.main]]
    name = "Contact"
    weight = 3
    url  = "contact"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Home"
    weight = 1
    url = "http://www.fresbinthomas.com"
